default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  port: 5432
  host: db
  username: postgres

development:
  <<: *default
  database: docker-rails-school_development

test:
  <<: *default
  database: docker-rails-school_test

production:
  <<: *default
  database: docker-rails-school_production